version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:12.6
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            sudo npm install -g
  test:
    docker:
        - image: cimg/node:12.6
    steps:
      - checkout
      - run:
          name: Running integration tests
          command: |
            sudo npm run test
workflows:
  build:
    jobs:
      - build
      - test:
          requires:
            - build